In [37]:
import os
import pandas as pd
import re
from bs4 import BeautifulSoup
import string, time

In [38]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [39]:
def clean_text(text):
    text = BeautifulSoup(text, "html.parser").get_text()
    text = re.sub(r"https?://\S+|www\.\S+", "", text)
    text = text.translate(
        str.maketrans("", "", string.punctuation)
    )
    text = re.sub(r"\s+", " ", text)
    text = text.lower()
    return text

In [40]:
df = pd.read_csv("../Dataset/IMDB Dataset.csv")

In [41]:
th = pd.read_csv("../Dataset/Twitter sentiment analysis: Hatred speech/train.csv")

In [42]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [43]:
df["review"] = df["review"].apply(clean_text)

In [44]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [45]:
text1 = 'Check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb'

text2 = 'Check out my notebook http://www.kaggle.com/campusx/notebook8223fc1abb'

text3 = 'Google search here www.google.com'

text4 = 'For notebook click https://www.kaggle.com/campusx/notebook8223fc1abb to search check www.google.com'

In [46]:
clean_text(text4)

'for notebook click to search check '

In [47]:
th.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [48]:
print(th.loc[31957, "tweet"])

ate @user isz that youuu?ðððððððððâ¤ï¸

In [49]:
th["tweet"] = th["tweet"].apply(clean_text)

In [50]:
th

          id  label                                              tweet
0          1      0   user when a father is dysfunctional and is so...
1          2      0  user user thanks for lyft credit i cant use ca...
2          3      0                                bihday your majesty
3          4      0  model i love u take with u all the time in urð...
4          5      0                  factsguide society now motivation
...      ...    ...                                                ...
31957  31958      0  ate user isz that youuuðððððð...
31958  31959      0   to see nina turner on the airwaves trying to ...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  user sikh temple vandalised in in calgary wso ...
31961  31962      0                     thank you user for you follow

[31962 rows x 3 columns]