In [111]:
import os
import pandas as pd
import re
from bs4 import BeautifulSoup
import string, time
import json

In [112]:
from slang import slang_dict

In [113]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [114]:
# with open("../Dataset/slang.json", "r", encoding="utf-8") as f:
#     slang_dict = json.load(f)

In [115]:
def expand_slang(text):
    words = text.split()

    expanded = [
        slang_dict.get(word, word)
        for word in words
    ]

    return " ".join(expanded)

In [116]:
expand_slang('IMHO')

'In My Honest/Humble Opinion'

In [117]:
def clean_text(text):
    text = BeautifulSoup(text, "html.parser").get_text()
    text = re.sub(r"https?://\S+|www\.\S+", "", text)
    text = text.translate(
        str.maketrans("", "", string.punctuation)
    )
    text = re.sub(r"\s+", " ", text)
    text = text.lower()
    return text

In [118]:
def remove_stopwords(text):
    new_text = []
    
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
        
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [119]:
df = pd.read_csv("../Dataset/IMDB Dataset.csv")

In [120]:
th = pd.read_csv("../Dataset/Twitter sentiment analysis: Hatred speech/train.csv")

In [121]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [122]:
df["review"] = df["review"].apply(clean_text)

In [123]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [124]:
text1 = 'Check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb'

text2 = 'Check out my notebook http://www.kaggle.com/campusx/notebook8223fc1abb'

text3 = 'Google search here www.google.com'

text4 = 'For notebook click https://www.kaggle.com/campusx/notebook8223fc1abb to search check www.google.com'

In [125]:
clean_text(text4)

'for notebook click to search check '

In [126]:
th.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [127]:
print(th.loc[31957, "tweet"])

ate @user isz that youuu?ðððððððððâ¤ï¸

In [128]:
th["tweet"] = th["tweet"].apply(clean_text)

In [129]:
th

          id  label                                              tweet
0          1      0   user when a father is dysfunctional and is so...
1          2      0  user user thanks for lyft credit i cant use ca...
2          3      0                                bihday your majesty
3          4      0  model i love u take with u all the time in urð...
4          5      0                  factsguide society now motivation
...      ...    ...                                                ...
31957  31958      0  ate user isz that youuuðððððð...
31958  31959      0   to see nina turner on the airwaves trying to ...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  user sikh temple vandalised in in calgary wso ...
31961  31962      0                     thank you user for you follow

[31962 rows x 3 columns]

In [130]:
from textblob import TextBlob

In [131]:
incorrect_text = 'ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner.'

textBlb = TextBlob(incorrect_text)

textBlb.correct().string

'certain conditions during several generations are modified in the same manner.'

In [132]:
from nltk.corpus import stopwords

In [133]:
import nltk

# nltk.download('stopwords')
# nltk.download('punkt')
# nltk.download('punkt_tab')
# nltk.download("wordnet")
# nltk.download("omw-1.4")

In [134]:
import spacy.cli

# spacy.cli.download("en_core_web_sm")

In [135]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [136]:
import re

def remove_emoji(text):
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )

    return emoji_pattern.sub(r'', text)

In [137]:
text = "I love NLP 😍❤️🚀"

print(remove_emoji(text))

I love NLP

In [138]:
import emoji
print(emoji.demojize("Python is 🔥"))

Python is :fire:

In [139]:
print(emoji.demojize(text))

I love NLP :smiling_face_with_heart-eyes::red_heart::rocket:

# Tokenization

In [140]:
sent1 = 'I am going to delhi'

sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [141]:
sent2 = 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great'

sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [142]:
sent3 = 'I am going to delhi!'

sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [143]:
import re

sent3 = 'I am going to delhi!'

tokens = re.findall(r'\w+', sent3)

tokens

['I', 'am', 'going', 'to', 'delhi']

In [144]:
text = "Hello, world! NLP_2025 is fun."

In [145]:
from nltk.tokenize import word_tokenize

word_tokenize(text)

['Hello', ',', 'world', '!', 'NLP_2025', 'is', 'fun', '.']

### Best

In [146]:
import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp(text)

tokens = [token.text for token in doc]

tokens

['Hello', ',', 'world', '!', 'NLP_2025', 'is', 'fun', '.']

### Stemming

In [147]:
from nltk.stem.porter import PorterStemmer

In [148]:
ps = PorterStemmer()

def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [149]:
sample = "walk walks walking walked"

stem_words(sample)

'walk walk walk walk'

In [150]:
text = "He was running and eating at the same time. He has bad habit of swimming after playing long hours in the Sun"

In [160]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    words = word_tokenize(text)

    lemmas = [
        lemmatizer.lemmatize(word)
        for word in words
        if word.isalpha()
    ]

    return " ".join(lemmas)

In [161]:
print(lemmatize_text(text))

He wa running and eating at the same time He ha bad habit of swimming after playing long hour in the Sun

In [162]:
def lemmatize_text(text):
    words = word_tokenize(text)

    print("\n=== Lemmatization ===")

    lemmas = []

    for word in words:
        if word.isalpha():
            lemma = lemmatizer.lemmatize(word, pos='v')

            if word != lemma:
                print(f"{word:15} -> {lemma}")

            lemmas.append(lemma)

    return " ".join(lemmas)

In [163]:
print(lemmatize_text(text))

=== Lemmatization ===
was             -> be
running         -> run
eating          -> eat
has             -> have
swimming        -> swim
playing         -> play
He be run and eat at the same time He have bad habit of swim after play long hours in the Sun

### Clean Text

In [ ]:
def clean_text(text):
    text = BeautifulSoup(text, "html.parser").get_text()
    text = re.sub(r"https?://\S+|www\.\S+", "", text)
    text = text.translate(
        str.maketrans("", "", string.punctuation)
    )
    text = re.sub(r"\s+", " ", text)

    text = expand_slang(text)
    print("After slang:", text)
    
    text = remove_stopwords(text)
    print("After stopwords:", text)
    
    text = lemmatize_text(text)
    print("After lemma:", text)

    text = text.lower()

    return text.strip()

In [156]:
clean_text(text)

After slang: He was running and eating at the same time He has bad habit of swimming after playing long hours in the Sun
After stopwords: He  running  eating    time He  bad habit  swimming  playing long hours   Sun
After lemma: He running eating time He bad habit swimming playing long hour Sun

'he running eating time he bad habit swimming playing long hour sun'