In [1]:
# pip install spacy

In [2]:
import spacy

In [3]:
# !python -m spacy validate

In [4]:
# !python -m spacy download en_core_web_sm

In [5]:
nlp = spacy.load("en_core_web_sm")

In [6]:
doc = nlp("I will google about facebook")

In [7]:
doc.text

'I will google about facebook'

In [8]:
{doc[0] : doc[0].pos_}, {doc[1] : doc[1].pos_}, {doc[2] : doc[2].pos_}, {doc[3] : doc[3].pos_}, {doc[4] : doc[4].pos_},

({I: 'PRON'},
 {will: 'AUX'},
 {google: 'VERB'},
 {about: 'ADP'},
 {facebook: 'PROPN'})

In [9]:
[{doc[0] : {doc[0].tag_, spacy.explain(doc[0].tag_)}}, 
{doc[1] : {doc[1].tag_, spacy.explain(doc[1].tag_)}}, 
{doc[2] : {doc[2].tag_, spacy.explain(doc[2].tag_)}}, 
{doc[3] : {doc[3].tag_, spacy.explain(doc[3].tag_)}}, 
{doc[4] : {doc[4].tag_, spacy.explain(doc[4].tag_)}}]

[{I: {'PRP', 'pronoun, personal'}},
 {will: {'MD', 'verb, modal auxiliary'}},
 {google: {'VB', 'verb, base form'}},
 {about: {'IN', 'conjunction, subordinating or preposition'}},
 {facebook: {'NNP', 'noun, proper singular'}}]

In [10]:
def get_pos_tags(text):
    for token in doc:
        print(
            {
                token.text: {
                    token.tag_,
                    spacy.explain(token.tag_)
                }
            }
        )

In [11]:
get_pos_tags(doc)

{'I': {'PRP', 'pronoun, personal'}}
{'will': {'MD', 'verb, modal auxiliary'}}
{'google': {'verb, base form', 'VB'}}
{'about': {'IN', 'conjunction, subordinating or preposition'}}
{'facebook': {'NNP', 'noun, proper singular'}}

In [12]:
import pandas as pd

def get_pos_tags(text):
    doc = nlp(text)

    data = []

    for token in doc:
        data.append({
            "Word": token.text,
            "Tag": token.tag_,
            "Meaning": spacy.explain(token.tag_)
        })

    return pd.DataFrame(data)

In [13]:
get_pos_tags(doc)

       Word  Tag                                    Meaning
0         I  PRP                          pronoun, personal
1      will   MD                      verb, modal auxiliary
2    google   VB                            verb, base form
3     about   IN  conjunction, subordinating or preposition
4  facebook  NNP                      noun, proper singular

In [14]:
get_pos_tags("I left the room")

   Word  Tag                 Meaning
0     I  PRP       pronoun, personal
1  left  VBD        verb, past tense
2   the   DT              determiner
3  room   NN  noun, singular or mass

In [15]:
get_pos_tags("to the left of the room")

   Word Tag                                    Meaning
0    to  IN  conjunction, subordinating or preposition
1   the  DT                                 determiner
2  left  NN                     noun, singular or mass
3    of  IN  conjunction, subordinating or preposition
4   the  DT                                 determiner
5  room  NN                     noun, singular or mass

In [16]:
get_pos_tags("I read books on history")

      Word  Tag                                    Meaning
0        I  PRP                          pronoun, personal
1     read  VBP      verb, non-3rd person singular present
2    books  NNS                               noun, plural
3       on   IN  conjunction, subordinating or preposition
4  history   NN                     noun, singular or mass

In [17]:
get_pos_tags("I have a read a book history")

      Word  Tag                                Meaning
0        I  PRP                      pronoun, personal
1     have  VBP  verb, non-3rd person singular present
2        a   DT                             determiner
3     read   NN                 noun, singular or mass
4        a   DT                             determiner
5     book   NN                 noun, singular or mass
6  history   NN                 noun, singular or mass

In [18]:
from spacy import displacy

In [19]:
doc = get_pos_tags("The quick brown fox jumped over the lazy dog")

In [20]:
displacy.render(nlp("The quick brown fox jumped over the lazy dog"), style="dep", jupyter=True)

In [21]:
options = {
    "distance" : 160,
    "compact"  : True,
    "color"    : '#fff',
    "bg"       : '#00a65a'
}

In [22]:
displacy.render(nlp("The quick brown fox jumped over the lazy dog"), style="dep", jupyter=True, options=options)

In [23]:
get_pos_tags("The quick brown fox jumped over the lazy dog")

     Word  Tag                                            Meaning
0     The   DT                                         determiner
1   quick   JJ  adjective (English), other noun-modifier (Chin...
2   brown   JJ  adjective (English), other noun-modifier (Chin...
3     fox   NN                             noun, singular or mass
4  jumped  VBD                                   verb, past tense
5    over   IN          conjunction, subordinating or preposition
6     the   DT                                         determiner
7    lazy   JJ  adjective (English), other noun-modifier (Chin...
8     dog   NN                             noun, singular or mass